name: mutation test

on:
  pull_request:

  push:

jobs:
  mutation:
    uses: yiisoft/actions/.github/workflows/roave-infection.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.2']
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
